/**
 * Croploo Signals — a free weekly newsletter (no Croploo account
 * required to subscribe), generated by CullyAI from the same real data
 * already computed elsewhere (proactive insights, cross-asset
 * synthesis). This is the top-of-funnel: newsletter → free trial → paid.
 */
import { pool } from "./db.js";
import { complete } from "./anthropicClient.js";
import { sendNewsletterEmail } from "./mailer.js";
import * as proactiveInsights from "./proactiveInsights.js";
import * as crossAssetSynthesis from "./crossAssetSynthesis.js";

export class NewsletterError extends Error {}

function mondayOfThisWeek() {
  const d = new Date();
  const day = d.getUTCDay();
  const diff = (day === 0 ? -6 : 1) - day;
  d.setUTCDate(d.getUTCDate() + diff);
  return d.toISOString().slice(0, 10);
}

async function generateSignals() {
  const [insights, synthesis] = await Promise.all([
    proactiveInsights.today().catch(() => null),
    crossAssetSynthesis.snapshot().catch(() => null),
  ]);

  const facts = [];
  if (insights) facts.push(...insights.insights);
  if (synthesis) {
    for (const [commodity, note] of Object.entries(synthesis.commentary)) {
      facts.push(`${commodity}: ${note}`);
    }
  }
  if (facts.length === 0) throw new NewsletterError("No signals available to build an issue");

  const system =
    "You are CullyAI writing the weekly 'Croploo Signals' newsletter for grain traders. " +
    "From the facts given, pick and rewrite exactly 5 of the most important as short, " +
    "punchy one-sentence signals. Respond with exactly 5 lines, no numbering, no markdown.";
  const text = await complete({
    system,
    messages: [{ role: "user", content: facts.join("\n") }],
    maxTokens: 500,
  });
  return text.split("\n").map((l) => l.trim()).filter(Boolean).slice(0, 5);
}

export async function latestIssue() {
  const issueDate = mondayOfThisWeek();
  const [rows] = await pool.query(
    "SELECT ai_json FROM newsletter_issues WHERE issue_date = ?",
    [issueDate]
  );
  if (rows.length > 0) return { issue_date: issueDate, signals: rows[0].ai_json };

  const signals = await generateSignals();
  await pool.query(
    `INSERT INTO newsletter_issues (issue_date, ai_json) VALUES (?, ?)
     ON DUPLICATE KEY UPDATE ai_json = VALUES(ai_json)`,
    [issueDate, JSON.stringify(signals)]
  );
  return { issue_date: issueDate, signals };
}

export async function subscribe(email) {
  if (!email || !email.includes("@")) throw new NewsletterError("Valid email required");
  await pool.query(
    "INSERT IGNORE INTO newsletter_subscribers (email) VALUES (?)",
    [email.toLowerCase().trim()]
  );
}

export async function unsubscribe(email) {
  await pool.query("DELETE FROM newsletter_subscribers WHERE email = ?", [
    email.toLowerCase().trim(),
  ]);
}

/** Sends this week's issue to every subscriber who hasn't received it yet. */
export async function sendWeeklyIssue() {
  const issue = await latestIssue();
  const [issueRows] = await pool.query(
    "SELECT id, sent_at FROM newsletter_issues WHERE issue_date = ?",
    [issue.issue_date]
  );
  if (issueRows[0]?.sent_at) return { sent: 0, already_sent: true };

  const [subscribers] = await pool.query(
    "SELECT email FROM newsletter_subscribers WHERE confirmed = TRUE"
  );
  for (const { email } of subscribers) {
    await sendNewsletterEmail(email, issue);
  }
  await pool.query("UPDATE newsletter_issues SET sent_at = NOW() WHERE issue_date = ?", [
    issue.issue_date,
  ]);
  return { sent: subscribers.length, already_sent: false };
}
